### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by FRBFStudios** [elnexreal/menuloop_randomizer#10]
1. Would it be possible to automatically remove the .mp3 suffix from the "Now playing: " display? Or maybe even make the display use the file's "title" attribute instead of the file name if there is one.
2. An option to make that display use the pusab font like the other menu texts would also be really nice.

I would really appreciate if any of these features were implemented!

**Comment by RayDeeUx** [comment]
Both have been added in v1.4.0, I just need to clean things up real quick.
