### ISSUE TITLE
(Android64) Crash on startup on v1.3.0

### ISSUE THREAD

**Issue by MrKareem1980** [elnexreal/menuloop_randomizer#11]
I just updated the mod and it worked great before but now it crashes the game on the loading screen.

A video showing

https://github.com/user-attachments/assets/d380ad06-6bfe-438b-a6f8-c5ef9d0b1ebd

I couldn't find anything in the crashlog folder but this is what was in the logs folder
https://github.com/user-attachments/files/16562345/Geode.2024-08-09.15.14.22.log

**Comment by RayDeeUx** [comment]
Fixed in v1.4.0.

@ninxout did an oopsie when attempting to support songs from the music library which has been removed. music library and newgrounds songs are in the same area in-game.
