### ISSUE TITLE
Question: Is there somewhere where you can still see the song thats currently playing after the initial "now playing" notification disappears?

### ISSUE THREAD

**Issue by AlphaQuata** [elnexreal/menuloop_randomizer#13]
sometimes a really good song comes on and im like oooOOo wahts that one called, but i either forgot what it had said on the "now playing" notification or i had never seen the notification because i had exited out of a level.  In previous versions, the "now playing" notification came back whenever you exited to the main menu and it was really convenient, but it seems to not work like that anymore in the latest version. I know i could just downgrade the mod back to an older version, but i was just wondering if there was already a way to see the song name repeatedly in the newest version.

**Comment by Aural0** [comment]
Unfortunately there isnt i wish there was it imo its worse in this version than before because you cant re trigger the notification again

**Comment by Hanifinio** [comment]
> sometimes a really good song comes on and im like oooOOo wahts that one called, but i either forgot what it had said on the "now playing" notification or i had never seen the notification because i had exited out of a level. In previous versions, the "now playing" notification came back whenever you exited to the main menu and it was really convenient, but it seems to not work like that anymore in the latest version. I know i could just downgrade the mod back to an older version, but i was just wondering if there was already a way to see the song name repeatedly in the newest version.

I was thinking maybe a panel or an already existing menu could include a 'Now Playing: xyz' kind of popup. Just copying EditorMusic

**Comment by AlphaQuata** [comment]
yeah that would completely fix everything

**Comment by RayDeeUx** [comment]
will add one in a moment give me a few days

**Comment by RayDeeUx** [comment]
@AlphaQuata @Hanifinio i am not an artist and i cannot afford photoshop. this is the best i can do
![image](https://github.com/user-attachments/assets/7723b0aa-3f4d-484d-a7ed-1db53f1e06a4)
should be in v1.4.1 :D

**Comment by AlphaQuata** [comment]
goated 👍

**Comment by Hanifinio** [comment]
> @AlphaQuata @Hanifinio i am not an artist and i cannot afford photoshop. this is the best i can do ![image](https://private-user-images.githubusercontent.com/51521765/361099220-7723b0aa-3f4d-484d-a7ed-1db53f1e06a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTQwNDMsIm5iZiI6MTcyNDQ5Mzc0MywicGF0aCI6Ii81MTUyMTc2NS8zNjEwOTkyMjAtNzcyM2IwYWEtM2Y0ZC00ODRkLWE3ZWQtMWRiNTNmMWUwNmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDEwMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTQyMjI5ZWJhYTUyY2MxMDc2NTFjMDcxYzBmNDZjZmMxMjNkNzJhZTM1NzAyOTcwZTRjNTQ0MjhiOGNiODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0YL_1hXFtJJsXN3HD5doz4RbjnjXnv4kKvoW1zDunK0) should be in v1.4.1 :D

That makes it even better
