### ISSUE TITLE
(Windows 10) Custom songs issue

### ISSUE THREAD

**Issue by zyiux** [elnexreal/menuloop_randomizer#7]
hi, i have an issue with this mod, there is many songs that the mod just don't play, i have 7 songs (all mp3) and 5 of them plays :c .

**Comment by RayDeeUx** [comment]
mess around with [FFMpeg](https://ffmpeg.org/). something must have gone wrong with how your mp3 files are built.

alternatively, feel free to try other audio file formats this mod supports: `.wav`, `.ogg`/`.oga`, or `.flac`
